const goods = {
    'metal': {'ingredients': [], 'duration': 60},
    'wood': {'ingredients': [], 'duration': 180},
    'plastic': {'ingredients': [], 'duration': 540},
    'seeds': {'ingredients': [], 'duration': 1200},
    'minerals': {'ingredients': [], 'duration': 1800},
    'chemicals': {'ingredients': [], 'duration': 7200},
    'toilet paper rolls': {'ingredients': [], 'duration': 10800},
    'sugar&spices': {'ingredients': [], 'duration': 14400},
    'glass': {'ingredients': [], 'duration': 18000, 'singular': 'glass'},
    'animal feed': {'ingredients': [], 'duration': 21600},
    'nails': {'ingredients': [{'metal': 2}], 'duration': 270},
    'wood planks': {'ingredients': [{'wood': 2}], 'duration': 1620},
    'bricks': {'ingredients': [{'minerals': 2}], 'duration': 1080},
    'cement': {'ingredients': [{'minerals': 2}, {'chemicals': 1}], 'duration': 2700},
    'glue': {'ingredients': [{'plastic': 1}, {'chemicals': 2}], 'duration': 3240},
    'paint': {'ingredients': [{'plastic': 1}, {'chemicals': 2}], 'duration': 3240},
    'hammers': {'ingredients': [{'wood': 2}], 'duration': 1620},
    'measuring tapes': {'ingredients': [{'plastic': 1}, {'metal': 1}], 'duration': 1080},
    'shovels': {'ingredients': [{'plastic': 1}, {'metal': 1}, {'wood': 1}], 'duration': 1620},
    'utensils': {'ingredients': [{'plastic': 2}, {'metal': 2}, {'wood': 2}], 'duration': 2430},
    'ladders': {'ingredients': [{'metal': 2}, {'wood planks': 2}], 'duration': 3240},
    'vegetables': {'ingredients': [{'seeds': 2}], 'duration': 1080},
    'flour': {'ingredients': [{'seeds': 2}, {'toilet paper rolls': 2}], 'duration': 1620},
    'fruit': {'ingredients': [{'seeds': 2}, {'tree': 1}], 'duration': 4860},
    'cream': {'ingredients': [{'animal feed': 1}], 'duration': 4020},
    'corn': {'ingredients': [{'minerals': 1}, {'seeds': 4}], 'duration': 3240},
    'cheese': {'ingredients': [{'animal feed': 2}], 'duration': 5640},
    'beef': {'ingredients': [{'animal feed': 3}], 'duration': 8100},
    'chairs': {'ingredients': [{'nails': 1}, {'hammers': 1}, {'wood': 2}], 'duration': 1080},
    'tables': {'ingredients': [{'wood planks': 1}, {'nails': 2}, {'hammer': 1}], 'duration': 1620},
    'kitchen/bathroom tiles': {'ingredients': [{'toilet paper rolls': 2}, {'measuring tape': 2}], 'duration': 4020},
    'cupboard': {'ingredients': [{'wood planks': 2}, {'glass': 2}, {'paint': 1}], 'duration': 2430},
    'grass': {'singular': 'grass', 'ingredients': [{'seeds': 1}, {'shovels': 1}], 'duration': 1800},
    'trees': {'ingredients': [{'seeds': 2}, {'shovels': 1}], 'duration': 5400},
    'outdoor furniture': {'ingredients': [{'plastic': 2}, {'toilet paper rolls': 2}, {'wood planks': 2}], 'duration': 8100},
    'donuts': {'ingredients': [{'flour': 1}, {'sugar&spices': 1}], 'duration': 2700},
    'smoothies': {'ingredients': [{'vegetables': 1}, {'fruit': 1}], 'duration': 1800},
    'bread rolls': {'ingredients': [{'flour': 2}, {'cream': 1}], 'duration': 3600},
    'cherry cheesecake slices': {'ingredients': [{'flour': 1}, {'fruit': 1}, {'cheese': 1}], 'duration': 5400},
    'baseball cap': {'ingredients': [{'toilet paper rolls': 2}, {'measuring tape': 1}], 'duration': 3600},
    'red shoes': {'ingredients': [{'plastic': 1}, {'glue': 1}, {'toilet paper rolls': 1}], 'duration': 4500},
    'watch': {'ingredients': [{'plastic': 2}, {'glass': 1}, {'chemical': 1}], 'duration': 5400},
    'fabric': {'ingredients': [], 'duration': 360},
    'reusable bags': {'ingredients': [{'fabric': 2}], 'duration': 1200},
    'ice cream sandwitches': {'singular': 'ice cream sandwitch', 'ingredients': [{'bread roll': 1}, {'cream': 1}], 'duration': 840},
};
export default goods;